<a href="https://colab.research.google.com/github/ny-essien/pytorch-tutorial-/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [3]:
my_list = [1,2,3,4]
print(my_list)

[1, 2, 3, 4]


In [4]:
multi_dim_list = [[1,2,3,4,5],[6,7,8,9,0]]
print(multi_dim_list)

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 0]]


In [5]:
### Numpy Array

In [6]:
np1 = np.random.rand(3,4)
np1

array([[0.10879645, 0.43974272, 0.78333533, 0.70957487],
       [0.90574401, 0.68294426, 0.69417203, 0.88894492],
       [0.1825051 , 0.9612049 , 0.08441918, 0.51156707]])

In [9]:
np1.dtype

dtype('float64')

In [10]:
type(np1)

numpy.ndarray

In [ ]:
####TENSOR

In [15]:
tensor_2d = torch.randn(3,4)
print(tensor_2d)
print(tensor_2d.dtype)

tensor([[-0.2665,  1.7181,  1.5491,  1.1280],
        [ 0.7095, -0.0972, -0.3914,  1.0679],
        [-0.8649, -0.4732, -0.1913, -0.1512]])
torch.float32


In [13]:
tensor_3d = torch.zeros(2,3,4)
print(tensor_3d)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [14]:
#### create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.1088, 0.4397, 0.7833, 0.7096],
        [0.9057, 0.6829, 0.6942, 0.8889],
        [0.1825, 0.9612, 0.0844, 0.5116]], dtype=torch.float64)