<a href="https://colab.research.google.com/github/ny-essien/pytorch-tutorial-/blob/main/Tensors_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

In [ ]:
my_torch = torch.arange(10)
print(my_torch)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
### reshaping tensor and view

my_torch = my_torch.reshape(2,5)
my_torch


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
#reshape if we don't know the number of items using -1
my_torch2 = torch.arange(10)
print(my_torch2)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
my_torch2 = my_torch2.reshape(2,-1)
my_torch2


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
#### using views
my_torch3 = torch.arange(10)
print(my_torch3)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
#when you make change to the original tensor
#with reshape and view in pytorch,the tensot gets updated
#for example

my_torch5 = torch.arange(10)
print(my_torch5)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
my_torch6 = my_torch5.reshape(2,5)
print(my_torch6)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [ ]:
my_torch5[3] = 21
print(my_torch5)
print(my_torch6)

tensor([ 0,  1,  2, 21,  4,  5,  6,  7,  8,  9])
tensor([[ 0,  1,  2, 21,  4],
        [ 5,  6,  7,  8,  9]])


In [16]:
###slices

my_torch7 = torch.arange(10)
print(my_torch7)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [17]:
###grabbing a specific item
my_torch8 = my_torch7.reshape(5,2)
print(my_torch8)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [19]:
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])